namespace: garrett_s_wininger
name: devtools
version: 1.0.0
readme: README.md
authors:
  - Garrett Wininger <garrett.s.wininger@outlook.com>
description: Personal collection for bootstrapping development environments.
license:
  - MIT
tags: []
dependencies: {}
repository: https://github.com/garrett-s-wininger/ansible-devtools
issues: https://github.com/garrett-s-wininger/ansible-devtools/issues
build_ignore: []
