---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Nim Compiler Status
      ansible.builtin.package:
        name: nim
        state: present
      check_mode: true
      register: nim_status

    - name: Assert Nim Installed
      ansible.builtin.assert:
        that: not nim_status.changed
