---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Prolog Interpreter Status
      ansible.builtin.package:
        name: swi-prolog
        state: present
      check_mode: true
      register: prolog_status

    - name: Assert Prolog Installed
      ansible.builtin.assert:
        that: not prolog_status.changed
