---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Ada Compiler Installation Status
      ansible.builtin.package:
        name: gnat
        state: present
      check_mode: true
      register: package_status

    - name: Test Compiler Installation
      ansible.builtin.assert:
        that: not package_status.changed
