---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Icon Interpreter Status
      ansible.builtin.package:
        name: icont
        state: present
      check_mode: true
      register: icon_status

    - name: Assert Icon Installed
      ansible.builtin.assert:
        that: not icon_status.changed
