---
- name: debian | Install OpenGL/Vulkan Libraries/Tooling
  ansible.builtin.apt:
    pkg:
      - libglfw3-dev
      - libglm-dev
      - libvulkan-dev
      - python3-pip
      - spirv-tools
      - vulkan-tools
      - vulkan-validationlayers-dev
    state: present
    update_cache: true

- name: debian | Install Pip Modules for OpenGL Extension Loading
  ansible.builtin.pip:
    name: glad
    state: present
