---
- name: Install OpenGL/Vulkan Libraries/Tooling
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - libglfw3-dev
    - libglm-dev
    - libvulkan-dev
    - python3-pip
    - spirv-tools
    - vulkan-tools
    - vulkan-validationlayers-dev

- name: Install Pip Modules for OpenGL Extension Loading
  ansible.builtin.pip:
    name: glad
