---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check C Compiler Status
      ansible.builtin.package:
        name: gcc
        state: present
      check_mode: yes
      register: c_compiler_status

    - name: Check C++ Compiler Status
      ansible.builtin.package:
        name: g++
        state: present
      register: cpp_compiler_status

    - name: Check Debugger Status
      ansible.builtin.package:
        name: gdb
        state: present
      register: debugger_status

    - name: Assert Packages Present
      ansible.builtin.assert:
        that:
          - not c_compiler_status.changed
          - not cpp_compiler_status.changed
          - not debugger_status.changed
