---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Common Lisp Installation Status
      ansible.builtin.package:
        name: sbcl
        state: present
      check_mode: true
      register: sbcl_status

    - name: Ensure Common Lisp is Present
      ansible.builtin.assert:
        that: 
          - not sbcl_status.changed
