---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check Racket Interpreter Status
      ansible.builtin.package:
        name: racket
        state: present
      check_mode: yes
      register: racket_status

    - name: Assert Racket Installed
      ansible.builtin.assert:
        that: not racket_status.changed
