---
- name: Install System Performance Tools
  ansible.builtin.apt:
    pkg:
      - bind9-dnsutils
      - bpfcc-tools
      - bpftrace
      - blktrace
      - cpuid
      - dmidecode
      - dstat
      - ethtool
      - fatrace
      - fio
      - hdparm
      - hping3
      - hwinfo
      - hwloc
      - ifstat
      - iftop
      - iotop
      - iperf3
      - lldpad
      - lshw
      - lsof
      - lsscsi
      - ltrace
      - msr-tools
      - mtr
      - nicstat
      - numactl
      - pchar
      - pciutils
      - schedtool
      - smartmontools
      - snmp
      - strace
      - sysbench
      - sysstat
      - tcpdump
      - tiptop
      - traceroute
      - util-linux
      - wireless-tools
    state: present
    update_cache: yes
